name: Lint code

on:
  push:
    branches:
      - main
  pull_request:
    paths:
      - "**"
      - "!**/*.md"
      - "!.github/**"
      - ".github/workflows/build.yml"
      - "!.vscode/**"
      - "!assets/**"
      - "!.gitignore"
      - "!**/*.nix"
      - "!**/flake.lock"

jobs:
  lint-qml:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/${{ github.repository_owner }}/shell-arch-env:latest

    steps:
      - name: Checkout source
        uses: actions/checkout@v7

      - name: CMake build
        run: |
          # Set version and git rev for CI build so we don't call git
          cmake -B build -G Ninja -DCMAKE_CXX_COMPILER=clazy -DVERSION= -DGIT_REVISION=
          cmake --build build

      - name: Lint QML
        shell: fish {0}
        run: |
          /usr/lib/qt6/bin/qmllint --version

          # Generate tooling
          touch .qmlls.ini
          QT_QPA_PLATFORM=offscreen QML2_IMPORT_PATH="$PWD/build/qml:$QML2_IMPORT_PATH" timeout 2 qs -p .

          # Construct linter args
          set -l build_dir (grep -oP "(?<=buildDir=\")(.*)(?=\")" .qmlls.ini)
          set -l import_paths (grep -oP "(?<=importPaths=\")(.*)(?=\")" .qmlls.ini | string split :)
          set -l args -I $build_dir
          for path in $import_paths
            set -a args -I $path
          end
          set -l qml_files (string match -vr 'build/.*' **.qml)

          # Lint
          set -l lint_out (/usr/lib/qt6/bin/qmllint --import disable $args $qml_files 2>&1 | tee /dev/stderr)
          test -z "$lint_out" || exit 1

  lint-cpp:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/${{ github.repository_owner }}/shell-arch-env:latest

    steps:
      - name: Checkout source
        uses: actions/checkout@v7

      - name: CMake build
        run: |
          cmake -B build -G Ninja -DCMAKE_CXX_COMPILER=clang++ -DCMAKE_EXPORT_COMPILE_COMMANDS=ON \
            -DCMAKE_DISABLE_PRECOMPILE_HEADERS=ON -DVERSION= -DGIT_REVISION=

      - name: Lint C++
        run: |
          clang-tidy --version
          run-clang-tidy -p build -quiet -j "$(nproc)" -warnings-as-errors='*' \
            -source-filter='^(?!.*/build/).*\.cpp$'
