# /* ---- 💫 https://github.com/JaKooLit 💫 ---- */  #
# /* wallust template - colors-kitty */

foreground         #ffffff
background         {{background}}
cursor             {{cursor}}

active_tab_foreground     {{background}}
active_tab_background     {{foreground}}
inactive_tab_foreground   {{foreground}}
inactive_tab_background   {{background}}

active_border_color   {{foreground}}
inactive_border_color {{background}}
bell_border_color     {{color1}}

color0      {{color0}}
color1      #ffffff
color2      #ffffff
color3      #ffffff
color4      #ffffff
color5      #ffffff
color6      #ffffff
color7      #ffffff
color8      #808080
color9      #ffffff
color10     #ffffff
color11     #ffffff
color12     #ffffff
color13     #ffffff
color14     #ffffff
color15     #ffffff

